CREATE DATABASE petition;


CREATE TABLE petition (
    IDP INT AUTO_INCREMENT PRIMARY KEY,
    Titre VARCHAR(255) NOT NULL,
    Description TEXT NOT NULL,
    DatePublic DATE NOT NULL,
    DateFinP DATE NOT NULL,
    PorteurP VARCHAR(100) NOT NULL,
    Email VARCHAR(255) NOT NULL
);

CREATE TABLE signature (
    IDS INT AUTO_INCREMENT PRIMARY KEY,
    IDP INT NOT NULL,
    Nom VARCHAR(100) NOT NULL,
    Prenom VARCHAR(100) NOT NULL,
    Pays VARCHAR(100) NOT NULL,
    Date DATE NOT NULL DEFAULT (CURRENT_DATE),
    Heure TIME NOT NULL DEFAULT (CURRENT_TIME),
    Email VARCHAR(255) NOT NULL,
    FOREIGN KEY (IDP) REFERENCES Petition(IDP) ON DELETE CASCADE
);
